const mainPuzzleLoopNum = 500
const numOfImages = 15
const cmToPSP = 28.3465 // CONVERTS centimetres TO POST SCRIPT POINTS
const fontPath = "public/fonts/groovy.ttf"
const watermarkImgPath = "public/assets/img/puzzle_imgs/watermark_img.png"
const dimensionsObjPath = "./utils/KDP_DimensionsObj.json"
const puzzleObjPath = "./utils/puzzleObj.json"

const previewManuscriptFolderPath = "public/assets/pmF74h226905sd5tgb21e1232sd/"
const fullManuscriptFolderPath = "./puzzleOutput/fm89d226005sd3521e1832sd/"

const imgDestFolderPath = "./puzzleOutput/dl/"
const mazeImgsFolderPath = "./puzzleOutput/maze/"
const fillominoImgsFolderPath = "./puzzleOutput/fillomino/"
const sudokuImgsFolderPath = "./puzzleOutput/sudoku/"
const hashiImgsFolderPath = "./puzzleOutput/hashi/"
const kakuroImgsFolderPath = "./puzzleOutput/kakuro/"
const masyuImgsFolderPath = "./puzzleOutput/masyu/"
const binaryImgsFolderPath = "./puzzleOutput/binary/"
const arithmagonImgsFolderPath = "./puzzleOutput/arithmagon/"
const mathSquaresImgsFolderPath = "./puzzleOutput/mathSquares/"
const tempmathSquareImgsFolderPath = "./puzzleOutput/tempmathSquares/"
const temp2mathSquareImgsFolderPath = "./puzzleOutput/temp2mathSquares/"
const kenkenImgsFolderPath = "./puzzleOutput/kenken/"
const reverseWordSearchImgsFolderPath = "./puzzleOutput/reverseWordSearch/"
const wordSearchImgsFolderPath = "./puzzleOutput/wordSearch/"
const tempWordSearchImgsFolderPath = "./puzzleOutput/tempWordSearch/"
const temp2WordSearchImgsFolderPath = "./puzzleOutput/temp2WordSearch/"
const tempReverseWordSearchImgsFolderPath = "./puzzleOutput/tempReverseWordSearch/"
const temp2ReverseWordSearchImgsFolderPath = "./puzzleOutput/temp2ReverseWordSearch/"
const cryptogramImgsFolderPath = "./puzzleOutput/cryptograms/"
const tempCryptogramImgsFolderPath = "./puzzleOutput/tempCryptograms/"
const temp2CryptogramImgsFolderPath = "./puzzleOutput/temp2Cryptograms/"
const crypticCrosswordImgsFolderPath = "./puzzleOutput/crypticCrosswords/"
const tempCrypticCrosswordImgsFolderPath = "./puzzleOutput/tempCrypticCrosswords/"
const temp2CrypticCrosswordImgsFolderPath = "./puzzleOutput/temp2CrypticCrosswords/"
const crosswordImgsFolderPath = "./puzzleOutput/crosswords/"
const nurikabeImgsFolderPath = "./puzzleOutput/nurikabe/"
const slitherLinkImgsFolderPath = "./puzzleOutput/slitherLink/"
const shakashakaImgsFolderPath = "./puzzleOutput/shakashaka/"
const nonogramImgsFolderPath = "./puzzleOutput/nonogram/"
const shikakuImgsFolderPath = "./puzzleOutput/shikaku/"
const stitchesImgsFolderPath = "./puzzleOutput/stitches/"
const shingokiImgsFolderPath = "./puzzleOutput/shingoki/"
const kakurasuImgsFolderPath = "./puzzleOutput/kakurasu/"
const hitoriImgsFolderPath = "./puzzleOutput/hitori/"

const puzzlerGeneratorManuscriptsID = "225785450071"
const puzzlerGeneratorImagesID = "226004269745"

const assortedManuscriptsID = "226160219178"
const mazeManuscriptsID = "225809946247"
const fillominoManuscriptsID = "225808771052"
const wordSearchManuscriptsID = "225811297572"
const crosswordManuscriptsID = "226140246829"

const mazeImagesID = "226005352183"
const fillominoImagesID = "226380340460"
const crosswordImagesID = "226004214127"
const sudokuImagesID = "231527581982"
const hashiImagesID = "231540988398"
const kakuroImagesID = "231545781564"
const masyuImagesID = "231558671033"
const binaryImagesID = "231553273333"
const arithmagonImagesID = "231563284413"
const mathSquaresImagesID = "231569183459"
const kenkenImagesID = "231574350321"
const wordSearchImagesID = "226004382702"
const reverseWordSearchImagesID = "231786666877"
const cryptogramImagesID = "231802636708"
const crypticCrosswordImagesID = "231805495164"
const nurikabeImagesID = "232099869241"
const slitherLinkImagesID = "232183703179"
const shakashakaImagesID = "232186914034"
const nonogramImagesID = "232188863421"
const shikakuImagesID = "232190515047"
const stitchesImagesID = "232191928688"
const shingokiImagesID = "232195518969"
const kakurasuImagesID = "232195463663"
const hitoriImagesID = "232196096976"

const BoxTokenDocId = "651379f8693e369829f72093"

const full_manuscript_folder_const = "fm89d226005sd3521e1832sd"
const prev_manuscript_folder_const = "pmF74h226905sd5tgb21e1232sd"

exports.full_manuscript_folder_const = full_manuscript_folder_const
exports.prev_manuscript_folder_const = prev_manuscript_folder_const

exports.mainPuzzleLoopNum = mainPuzzleLoopNum
exports.previewManuscriptFolderPath = previewManuscriptFolderPath
exports.fullManuscriptFolderPath = fullManuscriptFolderPath
exports.numOfImages = numOfImages
exports.cmToPSP = cmToPSP
exports.fontPath = fontPath
exports.watermarkImgPath = watermarkImgPath
exports.dimensionsObjPath = dimensionsObjPath
exports.puzzleObjPath = puzzleObjPath
exports.imgDestFolderPath = imgDestFolderPath
exports.mazeImgsFolderPath = mazeImgsFolderPath
exports.fillominoImgsFolderPath = fillominoImgsFolderPath
exports.sudokuImgsFolderPath = sudokuImgsFolderPath
exports.hashiImgsFolderPath = hashiImgsFolderPath
exports.kakuroImgsFolderPath = kakuroImgsFolderPath
exports.masyuImgsFolderPath = masyuImgsFolderPath
exports.binaryImgsFolderPath = binaryImgsFolderPath
exports.arithmagonImgsFolderPath = arithmagonImgsFolderPath
exports.mathSquaresImgsFolderPath = mathSquaresImgsFolderPath
exports.tempmathSquareImgsFolderPath = tempmathSquareImgsFolderPath
exports.temp2mathSquareImgsFolderPath = temp2mathSquareImgsFolderPath
exports.kenkenImgsFolderPath = kenkenImgsFolderPath
exports.wordSearchImgsFolderPath = wordSearchImgsFolderPath
exports.tempWordSearchImgsFolderPath = tempWordSearchImgsFolderPath
exports.temp2WordSearchImgsFolderPath = temp2WordSearchImgsFolderPath
exports.reverseWordSearchImgsFolderPath = reverseWordSearchImgsFolderPath
exports.tempReverseWordSearchImgsFolderPath = tempReverseWordSearchImgsFolderPath
exports.temp2ReverseWordSearchImgsFolderPath = temp2ReverseWordSearchImgsFolderPath
exports.cryptogramImgsFolderPath = cryptogramImgsFolderPath
exports.tempCryptogramImgsFolderPath = tempCryptogramImgsFolderPath
exports.temp2CryptogramImgsFolderPath = temp2CryptogramImgsFolderPath
exports.crypticCrosswordImgsFolderPath = crypticCrosswordImgsFolderPath
exports.tempCrypticCrosswordImgsFolderPath = tempCrypticCrosswordImgsFolderPath
exports.temp2CrypticCrosswordImgsFolderPath = temp2CrypticCrosswordImgsFolderPath
exports.crosswordImgsFolderPath = crosswordImgsFolderPath
exports.nurikabeImgsFolderPath = nurikabeImgsFolderPath
exports.slitherLinkImgsFolderPath = slitherLinkImgsFolderPath
exports.shakashakaImgsFolderPath = shakashakaImgsFolderPath
exports.nonogramImgsFolderPath = nonogramImgsFolderPath
exports.shikakuImgsFolderPath = shikakuImgsFolderPath
exports.stitchesImgsFolderPath = stitchesImgsFolderPath
exports.shingokiImgsFolderPath = shingokiImgsFolderPath
exports.kakurasuImgsFolderPath = kakurasuImgsFolderPath
exports.hitoriImgsFolderPath = hitoriImgsFolderPath

exports.puzzlerGeneratorManuscriptsID = puzzlerGeneratorManuscriptsID
exports.puzzlerGeneratorImagesID = puzzlerGeneratorImagesID
exports.assortedManuscriptsID = assortedManuscriptsID
exports.mazeManuscriptsID = mazeManuscriptsID
exports.fillominoManuscriptsID = fillominoManuscriptsID
exports.wordSearchManuscriptsID = wordSearchManuscriptsID
exports.crosswordManuscriptsID = crosswordManuscriptsID
exports.mazeImagesID = mazeImagesID
exports.fillominoImagesID = fillominoImagesID
exports.wordSearchImagesID = wordSearchImagesID
exports.crosswordImagesID = crosswordImagesID
exports.sudokuImagesID = sudokuImagesID
exports.hashiImagesID = hashiImagesID
exports.kakuroImagesID = kakuroImagesID
exports.masyuImagesID = masyuImagesID
exports.binaryImagesID = binaryImagesID
exports.arithmagonImagesID = arithmagonImagesID
exports.mathSquaresImagesID = mathSquaresImagesID
exports.kenkenImagesID = kenkenImagesID
exports.reverseWordSearchImagesID = reverseWordSearchImagesID
exports.cryptogramImagesID = cryptogramImagesID
exports.crypticCrosswordImagesID = crypticCrosswordImagesID
exports.nurikabeImagesID = nurikabeImagesID
exports.slitherLinkImagesID = slitherLinkImagesID
exports.shakashakaImagesID = shakashakaImagesID
exports.nonogramImagesID = nonogramImagesID
exports.shikakuImagesID = shikakuImagesID
exports.stitchesImagesID = stitchesImagesID
exports.shingokiImagesID = shingokiImagesID
exports.kakurasuImagesID = kakurasuImagesID
exports.hitoriImagesID = hitoriImagesID

exports.BoxTokenDocId = BoxTokenDocId

